### ISSUE TITLE
Missing docs for beta release

### ISSUE THREAD

**Issue by velinapetrova** [launchdarkly/erlang-server-sdk#18]
Hello all. Me and my team are researching the opportunity to integrated our projects with Launch Darkly. 
At present our main platform is running on Elixir on Phoenix stack.
I can see that the SDK is in early stage of development and just got pushed to a beta release. 

Do you have an estimated timeline when a stable version will come out?
Or at least add some basic documentation so we can test out the current release? 

Thank you

**Comment by hez** [comment]
@velinapetrova our team is using this library in production, it has been quite stable and would definitely recommend giving it a shot.

We also went and started an Elixir wrapper for it at https://github.com/pixelunion/elixir-launchdarkly if you all were interested in collaborating on it we'd be keen to see it extended.

Cheers

**Comment by bwoskow-ld** [comment]
Hi @velinapetrova ,

We will have a complete Erlang SDK reference guide available shortly, likely tomorrow. Once available it'll be accessible at https://docs.launchdarkly.com/sdk/server-side/erlang.

As for our timeline of transitioning the SDK from beta to GA -- the reason that it is not yet GA (general availability) is because the SDK is missing a core feature -- a persistent data store. Once we implement this functionality and verify that the SDK continues to meet our quality standards, we will release it to GA.

We've received a lot of positive feedback thus far with our alpha and beta releases of our Erlang SDK; while the SDK is not yet fully supported, we'd love to hear any feedback you have to help drive us to the initial supported release.

Cheers,
Ben

**Comment by bwoskow-ld** [comment]
The [docs](https://docs.launchdarkly.com/sdk/server-side/erlang) are now available.
